### ISSUE TITLE
broken link to repo for Schneider, Yurovsky, & Frank (2015)

### ISSUE THREAD

**Issue by oddmentations** [callab/callab.github.io#1]
I was hoping to take a look at the code for the analysis in **Schneider, R. M., Yurovsky, D., & Frank, M. C. (2015). Large-scale investigations of variability in children's first words** but link to the repo appears to be broken https://github.com/rosemschneider/firstword

**Comment by dyurovsky** [comment]
sorry, @misha-ash, I think the email associated with the lab github changed! You should be able to get it now: https://callab.github.io/publication/schneider-2015-large-scale/schneider-2015-large-scale.pdf
